#!/bin/bash

if [[ -z "$MAILTO" ]]; then
    MAILTO=root
fi
if [[ -z "$MAILFROM" ]]; then
    MAILFROM="systemd <root@$HOSTNAME>"
fi

sendmail -t -i <<MAIL
To: $MAILTO
From: $MAILFROM
Subject: systemd unit $1 failed
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$(systemctl status --full "$1")
MAIL
